ví dụ


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
rank_0_tensor= tf.constant(4)
print(rank_0_tensor)
r1=tf.constant(9,tf.int16)
print(r1)
r1_float=tf.constant(1.12,tf.float32)
print(r1_float)
r1_string=tf.constant("hello manh hiep",tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'hello manh hiep', shape=(), dtype=string)


## Bài tập 1: Tạo tensor kích thước [2, 3] với các phần tử được gán 0

In [ ]:
rows_1 = int(input("Nhập số hàng cho tensor (Bài tập 1): "))
cols_1 = int(input("Nhập số cột cho tensor (Bài tập 1): "))
tensor_zeros = tf.zeros([rows_1, cols_1])
print("Tensor với các phần tử 0:")
print(tensor_zeros)

Nhập số hàng cho tensor (Bài tập 1): 2
Nhập số cột cho tensor (Bài tập 1): 3
Tensor với các phần tử 0:
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


## Bài tập 2: Tạo tensor có kích thước và dtype như X với các phần tử được gán 0

In [ ]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_zeros_like_X = tf.zeros_like(X)
print("Tensor zero giống X:")
print(tensor_zeros_like_X)

Tensor zero giống X:
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


## Bài tập 3: Tạo tensor kích thước [3, 2] với các phần tử được gán 5

In [ ]:
rows_3 = int(input("Nhập số hàng cho tensor (Bài tập 3): "))
cols_3 = int(input("Nhập số cột cho tensor (Bài tập 3): "))
value_3 = float(input("Nhập giá trị phần tử cho tensor (Bài tập 3): "))
tensor_fives = tf.fill([rows_3, cols_3], value_3)
print("Tensor với các phần tử ", value_3, ":")
print(tensor_fives)

Nhập số hàng cho tensor (Bài tập 3): 3
Nhập số cột cho tensor (Bài tập 3): 5
Nhập giá trị phần tử cho tensor (Bài tập 3): 2
Tensor với các phần tử  2.0 :
tf.Tensor(
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]], shape=(3, 5), dtype=float32)


## Bài tập 4: Tạo tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
num_even_elements = int(input("Nhập số lượng phần tử chẵn bạn muốn tạo (Bài tập 4): "))
start_even = int(input("Nhập số chẵn bắt đầu (ví dụ: 6, để tạo 50 phần tử chẵn từ 6 trở đi): "))
even_numbers = tf.range(start_even, start_even + 2 * num_even_elements, 2)
print("Tensor 1-chiều với", num_even_elements, "phần tử chẵn:")
print(even_numbers)

Nhập số lượng phần tử chẵn bạn muốn tạo (Bài tập 4): 2
Nhập số chẵn bắt đầu (ví dụ: 6, để tạo 50 phần tử chẵn từ 6 trở đi): 2
Tensor 1-chiều với 2 phần tử chẵn:
tf.Tensor([2 4], shape=(2,), dtype=int32)


## Bài tập 5: Tạo tensor 1-chiều có giá trị như [10, 12, 14, ..., 100]

In [ ]:
start_range = int(input("Nhập giá trị bắt đầu cho tensor (Bài tập 5): "))
end_range = int(input("Nhập giá trị kết thúc (không bao gồm) cho tensor (Bài tập 5): "))
step_range = int(input("Nhập bước nhảy cho tensor (Bài tập 5): "))
tensor_range = tf.range(start_range, end_range + 1, step_range)
print("Tensor 1-chiều từ", start_range, "đến", end_range, "với bước nhảy", step_range, ":")
print(tensor_range)

Nhập giá trị bắt đầu cho tensor (Bài tập 5): 6
Nhập giá trị kết thúc (không bao gồm) cho tensor (Bài tập 5): 7
Nhập bước nhảy cho tensor (Bài tập 5): 8
Tensor 1-chiều từ 6 đến 7 với bước nhảy 8 :
tf.Tensor([6], shape=(1,), dtype=int32)


## Bài tập 6: Tạo tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0, standard deviation = 2

In [ ]:
rows_6 = int(input("Nhập số hàng cho tensor (Bài tập 6): "))
cols_6 = int(input("Nhập số cột cho tensor (Bài tập 6): "))
mean_6 = float(input("Nhập giá trị mean cho phân phối Normal (Bài tập 6): "))
stddev_6 = float(input("Nhập giá trị standard deviation cho phân phối Normal (Bài tập 6): "))
tensor_normal = tf.random.normal([rows_6, cols_6], mean=mean_6, stddev=stddev_6)
print("Tensor ngẫu nhiên phân phối Normal:")
print(tensor_normal)

Nhập số hàng cho tensor (Bài tập 6): 8
Nhập số cột cho tensor (Bài tập 6): 9
Nhập giá trị mean cho phân phối Normal (Bài tập 6): 10
Nhập giá trị standard deviation cho phân phối Normal (Bài tập 6): 1
Tensor ngẫu nhiên phân phối Normal:
tf.Tensor(
[[11.700173   9.59912    9.786187   9.848277   9.322432  11.076908
   7.8698015 11.114674   8.910707 ]
 [ 8.962034   8.838492  10.386954   8.745562  10.009025   9.555658
  11.444769   9.555235   9.502002 ]
 [10.089349  10.055504  11.968727   9.4841     9.411624  11.366354
  10.227321  10.021238  10.407967 ]
 [ 9.944993  10.292187   8.979918  10.004567   8.334085   9.040047
   8.872101   9.191806   9.306726 ]
 [11.868503   9.267838  11.530297   9.718488  10.5531025  8.508651
  11.053683  11.080222  11.146033 ]
 [10.90821   11.259823  10.261859   9.499159  10.486369  10.579097
   9.755546  10.26506   10.429419 ]
 [11.331442  10.729953   9.447279   9.425251   9.933459  12.1547365
  10.431319  10.873992   9.399108 ]
 [ 7.7384233  9.961147  11.2829

## Bài tập 7: Tạo tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi [0, 2]

In [ ]:
rows_7 = int(input("Nhập số hàng cho tensor (Bài tập 7): "))
cols_7 = int(input("Nhập số cột cho tensor (Bài tập 7): "))
minval_7 = float(input("Nhập giá trị minval cho phân phối Uniform (Bài tập 7): "))
maxval_7 = float(input("Nhập giá trị maxval cho phân phối Uniform (Bài tập 7): "))
tensor_uniform = tf.random.uniform([rows_7, cols_7], minval=minval_7, maxval=maxval_7)
print("Tensor ngẫu nhiên phân phối Uniform:")
print(tensor_uniform)

Nhập số hàng cho tensor (Bài tập 7): 5
Nhập số cột cho tensor (Bài tập 7): 6
Nhập giá trị minval cho phân phối Uniform (Bài tập 7): 7
Nhập giá trị maxval cho phân phối Uniform (Bài tập 7): 8
Tensor ngẫu nhiên phân phối Uniform:
tf.Tensor(
[[7.4664416 7.833621  7.812007  7.3801775 7.796162  7.5824947]
 [7.892413  7.8975363 7.014558  7.0808268 7.694106  7.0570908]
 [7.300078  7.6758513 7.8030252 7.761131  7.5516067 7.5068626]
 [7.832589  7.578557  7.407533  7.31116   7.743047  7.8321514]
 [7.8751507 7.0193286 7.7080317 7.8066797 7.039023  7.3606863]], shape=(5, 6), dtype=float32)


## Bài tập 8: Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng random_shuffle)

In [ ]:
rows_8 = int(input("Nhập số hàng cho tensor X (Bài tập 8): "))
cols_8 = int(input("Nhập số cột cho tensor X (Bài tập 8): "))
X_shuffle = tf.random.uniform([rows_8, cols_8], minval=0, maxval=10, dtype=tf.int32)
shuffled_X = tf.random.shuffle(X_shuffle)
print("Tensor X ban đầu (ngẫu nhiên):")
print(X_shuffle)
print("Tensor X sau khi shuffle theo chiều thứ nhất:")
print(shuffled_X)

Nhập số hàng cho tensor X (Bài tập 8): 1
Nhập số cột cho tensor X (Bài tập 8): 2
Tensor X ban đầu (ngẫu nhiên):
tf.Tensor([[6 1]], shape=(1, 2), dtype=int32)
Tensor X sau khi shuffle theo chiều thứ nhất:
tf.Tensor([[6 1]], shape=(1, 2), dtype=int32)


## Bài tập 9: Tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử dụng random_crop)

In [ ]:
orig_dim1 = int(input("Nhập kích thước chiều 1 của tensor gốc (ví dụ: 10) (Bài tập 9): "))
orig_dim2 = int(input("Nhập kích thước chiều 2 của tensor gốc (ví dụ: 10) (Bài tập 9): "))
orig_dim3 = int(input("Nhập kích thước chiều 3 của tensor gốc (ví dụ: 3) (Bài tập 9): "))

# Yêu cầu người dùng nhập kích thước cắt, nhưng đảm bảo không lớn hơn kích thước gốc
crop_dim1_input = int(input("Nhập kích thước chiều 1 của tensor cắt (phải <= " + str(orig_dim1) + ") (Bài tập 9): "))
crop_dim2_input = int(input("Nhập kích thước chiều 2 của tensor cắt (phải <= " + str(orig_dim2) + ") (Bài tập 9): "))
crop_dim3_input = int(input("Nhập kích thước chiều 3 của tensor cắt (phải <= " + str(orig_dim3) + ") (Bài tập 9): "))

# Đảm bảo kích thước cắt không vượt quá kích thước gốc
crop_dim1 = min(crop_dim1_input, orig_dim1)
crop_dim2 = min(crop_dim2_input, orig_dim2)
crop_dim3 = min(crop_dim3_input, orig_dim3)

random_image = tf.random.uniform([orig_dim1, orig_dim2, orig_dim3], minval=0, maxval=256, dtype=tf.int32)
cropped_image = tf.image.random_crop(random_image, size=[crop_dim1, crop_dim2, crop_dim3])
print("Tensor gốc kích thước (", orig_dim1, ", ", orig_dim2, ", ", orig_dim3, "):")
print(random_image.shape)
print("Tensor sau khi cắt ngẫu nhiên kích thước (", crop_dim1, ", ", crop_dim2, ", ", crop_dim3, "):")
print(cropped_image.shape)

Nhập kích thước chiều 1 của tensor gốc (ví dụ: 10) (Bài tập 9): 10
Nhập kích thước chiều 2 của tensor gốc (ví dụ: 10) (Bài tập 9): 10
Nhập kích thước chiều 3 của tensor gốc (ví dụ: 3) (Bài tập 9): 3
Nhập kích thước chiều 1 của tensor cắt (phải <= 10) (Bài tập 9): 6
Nhập kích thước chiều 2 của tensor cắt (phải <= 10) (Bài tập 9): 4
Nhập kích thước chiều 3 của tensor cắt (phải <= 3) (Bài tập 9): 2
Tensor gốc kích thước ( 10 ,  10 ,  3 ):
(10, 10, 3)
Tensor sau khi cắt ngẫu nhiên kích thước ( 6 ,  4 ,  2 ):
(6, 4, 2)


## Bài tập 10: Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y

In [ ]:
num_elements_10 = int(input("Nhập số phần tử cho hai tensor 1-chiều x, y (Bài tập 10): "))
min_val_10 = float(input("Nhập giá trị nhỏ nhất cho các phần tử (Bài tập 10): "))
max_val_10 = float(input("Nhập giá trị lớn nhất cho các phần tử (Bài tập 10): "))

x_ten = tf.random.uniform([num_elements_10], minval=min_val_10, maxval=max_val_10, dtype=tf.float32)
y_ten = tf.random.uniform([num_elements_10], minval=min_val_10, maxval=max_val_10, dtype=tf.float32)

result_ten = tf.where(tf.less(x_ten, y_ten), x_ten + y_ten, x_ten - y_ten)

print("Tensor x:", x_ten)
print("Tensor y:", y_ten)
print("Kết quả (x+y nếu x<y, x-y nếu x>y):")
print(result_ten)

Nhập số phần tử cho hai tensor 1-chiều x, y (Bài tập 10): 12
Nhập giá trị nhỏ nhất cho các phần tử (Bài tập 10): 12
Nhập giá trị lớn nhất cho các phần tử (Bài tập 10): 13
Tensor x: tf.Tensor(
[12.10658   12.681786  12.134641  12.987336  12.477996  12.136437
 12.79114   12.602637  12.70402   12.712586  12.2598095 12.424895 ], shape=(12,), dtype=float32)
Tensor y: tf.Tensor(
[12.515587  12.730036  12.149507  12.479041  12.680536  12.811419
 12.5295515 12.714999  12.131794  12.36359   12.684295  12.822056 ], shape=(12,), dtype=float32)
Kết quả (x+y nếu x<y, x-y nếu x>y):
tf.Tensor(
[24.622166   25.411821   24.284147    0.50829506 25.158531   24.947857
  0.2615881  25.317636    0.5722256   0.34899616 24.944103   25.246952  ], shape=(12,), dtype=float32)


## Bài tập 11: Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.

In [ ]:
minval_x = float(input("Nhập giá trị nhỏ nhất cho tensor x (Bài tập 11): "))
maxval_x = float(input("Nhập giá trị lớn nhất cho tensor x (Bài tập 11): "))
minval_y = float(input("Nhập giá trị nhỏ nhất cho tensor y (Bài tập 11): "))
maxval_y = float(input("Nhập giá trị lớn nhất cho tensor y (Bài tập 11): "))

x_eleven = tf.random.uniform([3, 2], minval=minval_x, maxval=maxval_x, dtype=tf.float32)
y_eleven = tf.random.uniform([2, 3], minval=minval_y, maxval=maxval_y, dtype=tf.float32)

print("Tensor x (3, 2):")
print(x_eleven)
print("Tensor y (2, 3):")
print(y_eleven)

diagonal_x = tf.linalg.diag_part(x_eleven)
print("Giá trị đường chéo của x:")
print(diagonal_x)

x_eleven_transposed = tf.transpose(x_eleven)
sum_x_y = x_eleven_transposed + y_eleven
print("Transpose của x (2, 3):")
print(x_eleven_transposed)
print("Kết quả x_transposed + y:")
print(sum_x_y)

Nhập giá trị nhỏ nhất cho tensor x (Bài tập 11): 8
Nhập giá trị lớn nhất cho tensor x (Bài tập 11): 7
Nhập giá trị nhỏ nhất cho tensor y (Bài tập 11): 0
Nhập giá trị lớn nhất cho tensor y (Bài tập 11): 9
Tensor x (3, 2):
tf.Tensor(
[[7.040965  7.6534266]
 [7.827818  7.1421175]
 [7.221368  7.2221947]], shape=(3, 2), dtype=float32)
Tensor y (2, 3):
tf.Tensor(
[[5.6944275 2.8021145 3.2636154]
 [1.5313997 5.3035364 6.14133  ]], shape=(2, 3), dtype=float32)
Giá trị đường chéo của x:
tf.Tensor([7.040965  7.1421175], shape=(2,), dtype=float32)
Transpose của x (2, 3):
tf.Tensor(
[[7.040965  7.827818  7.221368 ]
 [7.6534266 7.1421175 7.2221947]], shape=(2, 3), dtype=float32)
Kết quả x_transposed + y:
tf.Tensor(
[[12.735393 10.629932 10.484983]
 [ 9.184826 12.445654 13.363524]], shape=(2, 3), dtype=float32)


## Bài tập 12: Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng, trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.

In [ ]:
@tf.function
def create_random_tensors():
    x_twelve = tf.random.uniform([3, 2, 2], minval=0, maxval=10, dtype=tf.float32)
    y_twelve = tf.random.uniform([3, 2, 2], minval=0, maxval=10, dtype=tf.float32)
    return x_twelve, y_twelve

@tf.function
def add_tensors(a, b):
    return a + b

@tf.function
def subtract_tensors(a, b):
    return a - b

@tf.function
def multiply_tensors(a, b):
    return a * b

@tf.function
def divide_tensors(a, b):
    # Sử dụng tf.math.divide_no_nan để tránh lỗi chia cho 0
    return tf.math.divide_no_nan(a, b)

x_twelve_val, y_twelve_val = create_random_tensors()

print("Tensor x:")
print(x_twelve_val)
print("Tensor y:")
print(y_twelve_val)

print("Cộng:")
print(add_tensors(x_twelve_val, y_twelve_val))

print("Trừ:")
print(subtract_tensors(x_twelve_val, y_twelve_val))

print("Nhân:")
print(multiply_tensors(x_twelve_val, y_twelve_val))

print("Chia:")
print(divide_tensors(x_twelve_val, y_twelve_val))

Tensor x:
tf.Tensor(
[[[5.873498   0.46309114]
  [3.8714147  5.056658  ]]

 [[3.620534   1.4151645 ]
  [2.1582067  9.085622  ]]

 [[3.3914554  3.6992407 ]
  [0.20036459 3.4988356 ]]], shape=(3, 2, 2), dtype=float32)
Tensor y:
tf.Tensor(
[[[4.5045376 7.233609 ]
  [9.39502   1.6575599]]

 [[2.1987724 3.6415362]
  [6.415963  8.32453  ]]

 [[3.641361  5.392494 ]
  [4.612466  7.971306 ]]], shape=(3, 2, 2), dtype=float32)
Cộng:
tf.Tensor(
[[[10.378036   7.6967   ]
  [13.266434   6.7142177]]

 [[ 5.8193064  5.0567007]
  [ 8.57417   17.410152 ]]

 [[ 7.0328164  9.091735 ]
  [ 4.8128304 11.470141 ]]], shape=(3, 2, 2), dtype=float32)
Trừ:
tf.Tensor(
[[[ 1.3689604  -6.7705183 ]
  [-5.523605    3.399098  ]]

 [[ 1.4217615  -2.2263718 ]
  [-4.257756    0.7610922 ]]

 [[-0.24990559 -1.6932535 ]
  [-4.4121013  -4.4724703 ]]], shape=(3, 2, 2), dtype=float32)
Nhân:
tf.Tensor(
[[[26.457392    3.3498204 ]
  [36.372017    8.381713  ]]

 [[ 7.96073     5.153373  ]
  [13.846974   75.63353   ]]

 [[12.349513

## Bài tập 13: Xây dựng model để tính tổng hai tensor x, y

In [ ]:
@tf.function
def sum_model(x_thirteen, y_thirteen):
    return x_thirteen + y_thirteen

# Ví dụ sử dụng model
num_elements_13 = int(input("Nhập số phần tử cho hai tensor x, y (Bài tập 13): "))
min_val_13 = float(input("Nhập giá trị nhỏ nhất cho các phần tử (Bài tập 13): "))
max_val_13 = float(input("Nhập giá trị lớn nhất cho các phần tử (Bài tập 13): "))

x_thirteen_val = tf.random.uniform([num_elements_13], minval=min_val_13, maxval=max_val_13, dtype=tf.float32)
y_thirteen_val = tf.random.uniform([num_elements_13], minval=min_val_13, maxval=max_val_13, dtype=tf.float32)

print("Tensor x:", x_thirteen_val)
print("Tensor y:", y_thirteen_val)
print("Tổng hai tensor:", sum_model(x_thirteen_val, y_thirteen_val))

Nhập số phần tử cho hai tensor x, y (Bài tập 13): 2
Nhập giá trị nhỏ nhất cho các phần tử (Bài tập 13): 7
Nhập giá trị lớn nhất cho các phần tử (Bài tập 13): 8
Tensor x: tf.Tensor([7.8836656 7.92826  ], shape=(2,), dtype=float32)
Tensor y: tf.Tensor([7.3669686 7.1590853], shape=(2,), dtype=float32)
Tổng hai tensor: tf.Tensor([15.250634 15.087345], shape=(2,), dtype=float32)


## Bài tập 14: Xây dựng model để tính hiệu và tích hai tensor x, y

In [ ]:
@tf.function
def diff_and_prod_model(x_fourteen, y_fourteen):
    difference = x_fourteen - y_fourteen
    product = x_fourteen * y_fourteen
    return difference, product

# Ví dụ sử dụng model
num_elements_14 = int(input("Nhập số phần tử cho hai tensor x, y (Bài tập 14): "))
min_val_14 = float(input("Nhập giá trị nhỏ nhất cho các phần tử (Bài tập 14): "))
max_val_14 = float(input("Nhập giá trị lớn nhất cho các phần tử (Bài tập 14): "))

x_fourteen_val = tf.random.uniform([num_elements_14], minval=min_val_14, maxval=max_val_14, dtype=tf.float32)
y_fourteen_val = tf.random.uniform([num_elements_14], minval=min_val_14, maxval=max_val_14, dtype=tf.float32)

diff, prod = diff_and_prod_model(x_fourteen_val, y_fourteen_val)

print("Tensor x:", x_fourteen_val)
print("Tensor y:", y_fourteen_val)
print("Hiệu hai tensor:", diff)
print("Tích hai tensor:", prod)

Tensor x: tf.Tensor([10. 20.], shape=(2,), dtype=float32)
Tensor y: tf.Tensor([3. 5.], shape=(2,), dtype=float32)
Hiệu hai tensor: tf.Tensor([ 7. 15.], shape=(2,), dtype=float32)
Tích hai tensor: tf.Tensor([ 30. 100.], shape=(2,), dtype=float32)


## Bài tập 15: Xây dựng model để tính chu vi hình chữ nhật P = (a + b) * 2

In [ ]:
@tf.function
def rectangle_perimeter_model(a_fifteen, b_fifteen):
    return (a_fifteen + b_fifteen) * 2

# Ví dụ sử dụng model
length = tf.constant(float(input("Nhập chiều dài hình chữ nhật (Bài tập 15): ")), dtype=tf.float32)
width = tf.constant(float(input("Nhập chiều rộng hình chữ nhật (Bài tập 15): ")), dtype=tf.float32)

perimeter = rectangle_perimeter_model(length, width)
print("Chiều dài a:", length.numpy())
print("Chiều rộng b:", width.numpy())
print("Chu vi hình chữ nhật:", perimeter.numpy())

Chiều dài a: 5.0
Chiều rộng b: 3.0
Chu vi hình chữ nhật: 16.0


## Bài tập 16: Xây dựng model để tính diện tích toàn phần hình hộp chữ nhật

In [ ]:
@tf.function
def cuboid_surface_area_model(a_sixteen, b_sixteen, c_sixteen):
    s_xung_quanh = (a_sixteen + b_sixteen) * c_sixteen * 2
    s_toan_phan = (a_sixteen * b_sixteen) * 2 + s_xung_quanh
    return s_toan_phan, s_xung_quanh

# Ví dụ sử dụng model
length_c = tf.constant(float(input("Nhập chiều dài hình hộp chữ nhật (Bài tập 16): ")), dtype=tf.float32)
width_c = tf.constant(float(input("Nhập chiều rộng hình hộp chữ nhật (Bài tập 16): ")), dtype=tf.float32)
height_c = tf.constant(float(input("Nhập chiều cao hình hộp chữ nhật (Bài tập 16): ")), dtype=tf.float32)

total_area, lateral_area = cuboid_surface_area_model(length_c, width_c, height_c)

print("Chiều dài a:", length_c.numpy())
print("Chiều rộng b:", width_c.numpy())
print("Chiều cao c:", height_c.numpy())
print("Diện tích xung quanh hình hộp chữ nhật:", lateral_area.numpy())
print("Diện tích toàn phần hình hộp chữ nhật:", total_area.numpy())

Chiều dài a: 4.0
Chiều rộng b: 2.0
Chiều cao c: 3.0
Diện tích xung quanh hình hộp chữ nhật: 36.0
Diện tích toàn phần hình hộp chữ nhật: 52.0


## Bài tập 17: Xây dựng model chứng minh hai cạnh bên hình thang song song theo điều kiện

In [ ]:

@tf.function
def check_parallel_vectors(vec1, vec2, tolerance=1e-6):
    cross_product_2d = vec1[0] * vec2[1] - vec1[1] * vec2[0]
    is_parallel = tf.abs(cross_product_2d) < tolerance
    return is_parallel

# Ví dụ: Hai cạnh bên của hình thang (có thể không song song)
leg1_str = input("Nhập vector cạnh bên 1 dưới dạng 'x,y' (ví dụ: 1.0,2.0) (Bài tập 17): ")
leg1_coords = [float(x.strip()) for x in leg1_str.split(',')]
leg1 = tf.constant(leg1_coords, dtype=tf.float32)

leg2_str = input("Nhập vector cạnh bên 2 dưới dạng 'x,y' (ví dụ: 1.5,3.1) (Bài tập 17): ")
leg2_coords = [float(x.strip()) for x in leg2_str.split(',')]
leg2 = tf.constant(leg2_coords, dtype=tf.float32)

print("Vector cạnh bên 1:", leg1.numpy())
print("Vector cạnh bên 2:", leg2.numpy())
print("Hai cạnh bên có song song không?", check_parallel_vectors(leg1, leg2).numpy())

Vector cạnh bên 1: [1. 2.]
Vector cạnh bên 2: [1.5 3.1]
Hai cạnh bên có song song không (mong đợi False)? False

Vector cạnh đáy 1: [3. 0.]
Vector cạnh đáy 2: [6. 0.]
Hai cạnh đáy có song song không (mong đợi True)? True


## Bài tập 18: Xây dựng model chứng minh hai cạnh đáy hình thang bằng nhau theo điều kiện

In [ ]:


@tf.function
def check_equal_bases_model(base1_length, base2_length, tolerance=1e-6):
    return tf.abs(base1_length - base2_length) < tolerance

# Ví dụ: Các cạnh đáy của hình thang thông thường
base_a_input = float(input("Nhập độ dài cạnh đáy 1 (Bài tập 18): "))
base_b_input = float(input("Nhập độ dài cạnh đáy 2 (Bài tập 18): "))

base_a = tf.constant(base_a_input, dtype=tf.float32)
base_b = tf.constant(base_b_input, dtype=tf.float32)

print("Độ dài cạnh đáy 1:", base_a.numpy())
print("Độ dài cạnh đáy 2:", base_b.numpy())
print("Hai cạnh đáy có bằng nhau không?", check_equal_bases_model(base_a, base_b).numpy())

Độ dài cạnh đáy 1: 5.0
Độ dài cạnh đáy 2: 8.0
Hai cạnh đáy có bằng nhau không (mong đợi False)? False

Độ dài cạnh đáy 1: 7.0
Độ dài cạnh đáy 2: 7.0
Hai cạnh đáy có bằng nhau không (mong đợi True)? True


## Bài tập 19: Xây dựng model chứng minh NA = NC theo mô tả với AM, MB, AN, NC là đầu vào

In [ ]:
# Yêu cầu "chứng minh NA = NC" khi AM, MB, AN, NC là đầu vào ngụ ý rằng chúng ta chỉ cần kiểm tra sự bằng nhau của AN và NC.
# Không có mối liên hệ hình học cụ thể nào được mô tả liên quan đến AM và MB để "chứng minh" NA = NC dựa trên chúng.
# Do đó, model sẽ đơn giản là một hàm kiểm tra sự bằng nhau của hai giá trị AN và NC.

@tf.function
def prove_na_equals_nc_model(AM, MB, AN, NC, tolerance=1e-6):
    is_equal = tf.abs(AN - NC) < tolerance
    return is_equal

# Ví dụ sử dụng model
am_val = tf.constant(float(input("Nhập giá trị AM (Bài tập 19): ")), dtype=tf.float32)
mb_val = tf.constant(float(input("Nhập giá trị MB (Bài tập 19): ")), dtype=tf.float32)
an_val = tf.constant(float(input("Nhập giá trị AN (Bài tập 19): ")), dtype=tf.float32)
nc_val = tf.constant(float(input("Nhập giá trị NC (Bài tập 19): ")), dtype=tf.float32)

print("Giá trị AM:", am_val.numpy())
print("Giá trị MB:", mb_val.numpy())
print("Giá trị AN:", an_val.numpy())
print("Giá trị NC:", nc_val.numpy())
print("NA có bằng NC không?", prove_na_equals_nc_model(am_val, mb_val, an_val, nc_val).numpy())

Giá trị AM: 2.0
Giá trị MB: 3.0
Giá trị AN: 4.0
Giá trị NC: 4.0
NA có bằng NC không (mong đợi True)? True

Giá trị AN: 5.0
Giá trị NC: 6.0
NA có bằng NC không (mong đợi False)? False
