In [ ]:
%%capture
!pip install pymupdf

In [ ]:
import tensorflow as tf
import numpy as np

# 3.1. Tạo Tensor 0-chiều (scalar)
scalar_tensor = tf.constant(4)
print("Scalar Tensor:", scalar_tensor)

# Tạo với kiểu dữ liệu cụ thể
scalar_int16 = tf.constant(4, dtype=tf.int16)
scalar_float32 = tf.constant(4.0, dtype=tf.float32)
scalar_string = tf.constant("TensorFlow")

print("Scalar Int16:", scalar_int16)
print("Scalar Float32:", scalar_float32)
print("Scalar String:", scalar_string)

Scalar Tensor: tf.Tensor(4, shape=(), dtype=int32)
Scalar Int16: tf.Tensor(4, shape=(), dtype=int16)
Scalar Float32: tf.Tensor(4.0, shape=(), dtype=float32)
Scalar String: tf.Tensor(b'TensorFlow', shape=(), dtype=string)


In [ ]:
# 3.2. Tạo Tensor 1-chiều (vector)
vector_tensor = tf.constant([2.0, 3.0, 4.0])
print("Vector Tensor (1D):", vector_tensor)
print("Shape:", vector_tensor.shape)

Vector Tensor (1D): tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
Shape: (3,)


In [ ]:
# 3.3. Tạo Tensor 2-chiều (matrix)
matrix_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]])
print("Matrix Tensor (2D):\n", matrix_tensor.numpy())
print("Shape:", matrix_tensor.shape)

Matrix Tensor (2D):
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


In [ ]:
# 3.4. Tạo Tensor 3-chiều
tensor_3d = tf.constant([
  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],
])
print("Tensor 3D Shape:", tensor_3d.shape)

# 3.5. Thuộc tính của tensor
print("DType:", tensor_3d.dtype)
print("Number of dimensions:", tensor_3d.ndim)

Tensor 3D Shape: (3, 2, 5)
DType: <dtype: 'int32'>
Number of dimensions: 3


In [ ]:
# Bài 6: Tạo tensor [3, 2] ngẫu nhiên Normal (mean=0, stddev=2)
bai6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print("Bài 6:\n", bai6.numpy())

# Bài 7: Tạo tensor [3, 2] ngẫu nhiên Uniform trong khoảng [0, 2]
bai7 = tf.random.uniform([3, 2], minval=0, maxval=2)
print("\nBài 7:\n", bai7.numpy())

# Bài 8: Shuffle tensor X = [[1, 2], [3, 4], [5, 6]] theo chiều thứ nhất
X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
bai8 = tf.random.shuffle(X_8)
print("\nBài 8 (Shuffle):\n", bai8.numpy())

# Bài 9: Tạo tensor (10, 10, 3) và crop thành (5, 5, 3)
large_tensor = tf.random.uniform([10, 10, 3])
bai9 = tf.image.random_crop(large_tensor, size=[5, 5, 3])
print("\nBài 9 (Crop size):", bai9.shape)

# Bài 10: Hai tensor x, y (5 phần tử). Trả về x + y nếu x < y, ngược lại x - y
x = tf.random.uniform([5], minval=0, maxval=10)
y = tf.random.uniform([5], minval=0, maxval=10)
bai10 = tf.where(x < y, x + y, x - y)
print("\nBài 10:")
print("x: ", x.numpy())
print("y: ", y.numpy())
print("Kết quả: ", bai10.numpy())

Bài 6:
 [[-2.4766202 -0.601952 ]
 [ 1.0823492  0.173823 ]
 [ 1.2886236 -4.4374614]]

Bài 7:
 [[0.15745783 0.6285627 ]
 [1.9055641  0.9903445 ]
 [0.20009947 1.675772  ]]

Bài 8 (Shuffle):
 [[1 2]
 [3 4]
 [5 6]]

Bài 9 (Crop size): (5, 5, 3)

Bài 10:
x:  [6.159807  6.754552  6.172839  1.4595723 9.217836 ]
y:  [5.371889   6.190295   9.52011    0.77487946 0.7903254 ]
Kết quả:  [ 0.7879181   0.56425667 15.692949    0.68469286  8.427511  ]


In [ ]:
# Bài 11: x(3,2) [5,10], y(2,3) [15,20]. Giữ đường chéo x và x + y
x_11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y_11 = tf.random.uniform([2, 3], minval=15, maxval=20)
# Vì x không phải ma trận vuông, ta lấy đường chéo của phần vuông lớn nhất
diag_x = tf.linalg.diag_part(x_11)
# Thực hiện cộng (TensorFlow sẽ broadcast hoặc cần reshape tùy mục đích, ở đây ta cộng x và chuyển vị của y)
result_11 = x_11 + tf.transpose(y_11)
print("Bài 11 - Kết quả x + y.T:\n", result_11.numpy())

# Bài 12: Hàm tính toán trong Graph
@tf.function
def basic_ops(x, y):
    return x + y, x - y, x * y, x / y

x_12 = tf.random.uniform([3, 2, 2])
y_12 = tf.random.uniform([3, 2, 2])
add, sub, mul, div = basic_ops(x_12, y_12)
print("\nBài 12: Đã thực hiện tính toán trong graph.")

# Bài 13 & 14: Model tính tổng, hiệu, tích
class BasicModel(tf.Module):
    @tf.function
    def calculate(self, x, y):
        return x + y, x - y, x * y

model = BasicModel()
res_sum, res_sub, res_mul = model.calculate(tf.constant(10), tf.constant(5))
print(f"\nBài 13 & 14 (x=10, y=5): Tổng={res_sum}, Hiệu={res_sub}, Tích={res_mul}")

# Bài 15: Model tính chu vi P = (a + b) * 2
@tf.function
def tinh_chu_vi(a, b):
    return (a + b) * 2

print("\nBài 15 - Chu vi (a=5, b=10):", tinh_chu_vi(tf.constant(5), tf.constant(10)).numpy())

Bài 11 - Kết quả x + y.T:
 [[26.289156 26.486933]
 [25.28163  25.650934]
 [25.893385 26.779156]]

Bài 12: Đã thực hiện tính toán trong graph.

Bài 13 & 14 (x=10, y=5): Tổng=15, Hiệu=5, Tích=50

Bài 15 - Chu vi (a=5, b=10): 30


In [ ]:
# Bài 16: Model tính diện tích toàn phần hình hộp chữ nhật
@tf.function
def tinh_dien_tich_toan_phan(a, b, c):
    s_xung_quanh = (a + b) * c * 2
    s_toan_phan = (a * b) * 2 + s_xung_quanh
    return s_xung_quanh, s_toan_phan

s_xq, s_tp = tinh_dien_tich_toan_phan(tf.constant(3.0), tf.constant(4.0), tf.constant(5.0))
print("Bài 16 - S xung quanh:", s_xq.numpy(), ", S toàn phần:", s_tp.numpy())

# Bài 17 & 18: Model chứng minh tính chất hình thang
# Giả sử điều kiện song song hoặc bằng nhau được biểu diễn qua vector/tensor
@tf.function
def kiem_tra_hinh_thang(day_tren, day_duoi, canh_ben1, canh_ben2):
    # Ví dụ logic: nếu các vector hướng song song (tích vô hướng hoặc tỉ lệ)
    is_parallel = tf.reduce_all(tf.equal(day_tren / day_duoi, day_tren[0] / day_duoi[0]))
    return is_parallel

# Bài 19: Model chứng minh trung điểm (NA = NC)
@tf.function
def chung_minh_trung_diem(AN, NC):
    # Nếu AN - NC = 0 thì N là trung điểm AC
    is_midpoint = tf.abs(AN - NC) < 1e-6
    return is_midpoint



Bài 16 - S xung quanh: 70.0 , S toàn phần: 94.0


In [ ]:
# Bài 1: Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
bai1 = tf.zeros([2, 3])
print("Bài 1:\n", bai1.numpy())

# Bài 2: Cho X = [[1, 2, 3], [4, 5, 6]], tạo tensor kích thước và dtype như X với phần tử 0
X = [[1, 2, 3], [4, 5, 6]]
bai2 = tf.zeros_like(X)
print("\nBài 2:\n", bai2.numpy())

# Bài 3: Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
bai3 = tf.fill([3, 2], 5)
print("\nBài 3:\n", bai3.numpy())

# Bài 4: Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
# Lưu ý: Khoảng [5, 10] chỉ có các số chẵn là 6, 8, 10. Để có 50 phần tử, ta có thể dùng tf.repeat
even_numbers = [6, 8, 10]
bai4 = tf.repeat(even_numbers, repeats=[17, 17, 16]) # Tổng 50 phần tử
print("\nBài 4 (50 phần tử chẵn từ [5, 10]):\n", bai4.numpy())

# Bài 5: Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]
bai5 = tf.range(start=10, limit=101, delta=2)
print("\nBài 5:\n", bai5.numpy())

Bài 1:
 [[0. 0. 0.]
 [0. 0. 0.]]

Bài 2:
 [[0 0 0]
 [0 0 0]]

Bài 3:
 [[5 5]
 [5 5]
 [5 5]]

Bài 4 (50 phần tử chẵn từ [5, 10]):
 [ 6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10]

Bài 5:
 [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]
